import Image from "next/image";
import type { Metadata } from "next";
import { FaDiscord } from "react-icons/fa";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans">
      <main className="flex min-h-screen w-full max-w-4xl flex-col items-center justify-between py-32 px-16 bg-white sm:items-start">
        <div className="flex flex-col items-center gap-6 text-center sm:items-start sm:text-left">
          <h1 className="max-w-xs text-3xl font-semibold leading-10 tracking-tight text-black">
            ABOUT
          </h1>
          <p className="max-w-md text-lg leading-8 text-zinc-600">
            <b>Hoop Union</b> is a place that aggregates data from Francis and makes it publicly accessible on the internet.
          </p>
        </div>
        <div className="flex flex-col gap-4 text-base font-medium sm:flex-row">
          <a
            className="flex h-12 w-40 items-center justify-center gap-2 rounded-full bg-[#fea903] px-5 text-background transition-colors hover:bg-[#383838]"
            href="http://hoopfrontend-kohl.vercel.app/landing"
            target="_blank"
            rel="noopener noreferrer"
          >
            About <i>Francis</i>
          </a>
          <a
            className="flex h-12 w-40 flex-wrap items-center justify-center rounded-full border border-solid border-black/[.08] px-5 transition-colors hover:border-transparent hover:bg-black/[.04]"
            href=""
            target="_blank"
            rel="noopener noreferrer"
          >
              <span className="text-lg pr-1.5"><FaDiscord /></span> Join Discord 

          </a>
        </div>
      </main>
    </div>
  );
}
