'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//export const metadata: Metadata = {
//  title: "Hooper Union",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center bg-zinc-50">
          <div className="w-full max-w-4xl h-16 border-b-1 bg-white
            flex flex-row justify-start px-6 gap-4 items-center
            text-2xl text-foreground font-bold"
          >
            <a href="/" className={`
              ${"/" === pathname ? "italic" : ""}`}>
              Home
            </a>
            <a href="/about" className={`
              ${"/about" === pathname ? "italic" : ""}`}>
              About
            </a>
          </div>
        </div>
        {children}
        <div className="flex justify-center bg-zinc-50 mt-5">
          <div className="w-full max-w-4xl h-16 border-t-1 bg-white
            flex flex-row justify-between items-center
            text-md text-foreground px-6"
          >
            <div>A Francis company</div>
            <div>Copyright Francis 2026</div>
          </div>
        </div>
      </body>
    </html>
  );
}
