import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hoop Union",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
        <div className="flex justify-center bg-zinc-50">
          <div className="w-full max-w-4xl h-16 border-t-1 bg-white
            flex flex-row justify-between items-center
            text-md text-foreground px-6"
          >
            <div>A Francis company</div>
            <div>Copyright Francis 2026</div>
          </div>
        </div>
      </body>
    </html>
  );
}
